name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x
      - name: Publish
        run: dotnet publish MediaSession.Blazor.Sample/MediaSession.Blazor.Sample.csproj -c Release -o release
      - name: Config base address
        run: sed -i 's/<base href="\/" \/>/<base href="\/MediaSession.Blazor\/" \/>/g' release/wwwroot/index.html
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: release/wwwroot
