name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_ID: MediaSession.Blazor
      NUGET_SECRET: ${{ secrets.NUGET_SECRET }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.x

      - name: Package and Publish📦
        run: |
          VERSION=`git describe --tags`
          echo "Publishing Version: ${VERSION}"
          dotnet build
          dotnet pack $PACKAGE_ID/$PACKAGE_ID.csproj /p:PackageVersion=$VERSION -c Release -o publish
          dotnet nuget push publish/*.nupkg --api-key $GITHUB_TOKEN --source "github" --skip-duplicate
          dotnet nuget push publish/*.nupkg --api-key $NUGET_SECRET --source "https://api.nuget.org/v3/index.json" --skip-duplicate